[package]
name = "gnvim"
version = "0.1.0"
authors = ["Ville Hakulinen <ville.hakulinen@gmail.com>"]
edition = "2018"

[profile.dev]
debug = true

[features]
default = ["libwebkit2gtk"]

unstable = []
libwebkit2gtk = [
    "webkit2gtk",
    "pulldown-cmark",
    "ammonia",
    "syntect",
    "lazy_static",
]

[dependencies]
log = "0.4.8"
env_logger = "0.7.1"

structopt = "0.3"

gio = "0.7"
pango = "0.7"
pangocairo = "0.8"
cairo-rs = "0.7"
glib = "0.8"
gdk = "0.11"
gdk-pixbuf = "0.7"

pulldown-cmark = { version = "0.2", default-features = false, optional = true }
ammonia = { version = "2", optional = true }
syntect = { version = "3", optional = true }
lazy_static = {version = "1.3.0", optional = true }

[dependencies.gtk]
version = "0.7"
features = ["v3_18"]

[dependencies.webkit2gtk]
version = "0.8"
features = ["v2_14"]
optional = true

[dependencies.neovim-lib]
#git = "https://github.com/vhakulinen/neovim-lib"
git = "https://github.com/daa84/neovim-lib"
